// // Mocks generated by Mockito 5.4.4 from annotations
// // in new_nuntium/test/news_remote_data_source_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;

// import 'package:dio/dio.dart' as _i2;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:new_nuntium/core/models/article.dart' as _i5;
// import 'package:new_nuntium/core/network/api_client.dart' as _i6;
// import 'package:new_nuntium/features/home/data/data_source/news_remote_data_source.dart'
//     as _i3;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
//   _FakeResponse_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [NewsRemoteDataSource].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockNewsRemoteDataSource extends _i1.Mock
//     implements _i3.NewsRemoteDataSource {
//   MockNewsRemoteDataSource() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i4.Future<List<_i5.Article>> fetchTopHeadlines({
//     required String? category,
//     int? page = 1,
//     int? pageSize = 20,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #fetchTopHeadlines,
//           [],
//           {
//             #category: category,
//             #page: page,
//             #pageSize: pageSize,
//           },
//         ),
//         returnValue: _i4.Future<List<_i5.Article>>.value(<_i5.Article>[]),
//       ) as _i4.Future<List<_i5.Article>>);

//   @override
//   _i4.Future<List<_i5.Article>> searchNews({
//     required String? query,
//     int? page = 1,
//     int? pageSize = 20,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #searchNews,
//           [],
//           {
//             #query: query,
//             #page: page,
//             #pageSize: pageSize,
//           },
//         ),
//         returnValue: _i4.Future<List<_i5.Article>>.value(<_i5.Article>[]),
//       ) as _i4.Future<List<_i5.Article>>);
// }

// /// A class which mocks [ApiClient].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockApiClient extends _i1.Mock implements _i6.ApiClient {
//   MockApiClient() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i4.Future<_i2.Response<dynamic>> get(
//     String? path, {
//     Map<String, dynamic>? queryParams,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #get,
//           [path],
//           {#queryParams: queryParams},
//         ),
//         returnValue:
//             _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
//           this,
//           Invocation.method(
//             #get,
//             [path],
//             {#queryParams: queryParams},
//           ),
//         )),
//       ) as _i4.Future<_i2.Response<dynamic>>);
// }
