name: new_nuntium
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  easy_localization: ^3.0.7
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1
  pinput: ^6.0.1
  cached_network_image: ^3.4.1
  persistent_bottom_nav_bar_v2: ^6.2.0
  shared_preferences: ^2.5.4
  get_it: ^9.2.0
  webview_flutter: ^4.13.1

  # Network
  internet_connection_checker: ^1.0.0+1
  dio: ^5.9.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.0.0
  
  infinite_scroll_pagination: ^5.1.1
  pretty_dio_logger: ^1.4.0
  share_plus: ^12.0.1
  flutter_dotenv: ^5.1.0
  dev: ^1.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  logger: ^2.6.2
  dartz: ^0.10.1
  firebase_crashlytics: ^5.0.7
  lottie: ^3.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/images/vectors/
    - assets/translation/
    - .env

  fonts:
    - family: SP_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  
  # (Adaptive Icons) for modern devices
  adaptive_icon_background: "#2536A7" # (AppColors.purpleDarker)
  adaptive_icon_foreground: "assets/images/app_icon.png" 
  